### ISSUE TITLE
i got syntax error for wordlist -W command

### ISSUE THREAD

**Issue by VijaySokkala** [spinkham/skipfish#2]
command : 
skipfish -W /root/medium.txt  -S /root/medium.txt -o scanreports  http://zero.webappsecurity.com

Error: 
Wordlist '/root/medium.txt': syntax error in line 0.

could you pls help me out above issue

thank you in advance

**Comment by spinkham** [comment]
-W and -S can't point to the same file. -W should point to an empty or site specific file.
